---
platform: linux

image: docker:///datianshi/gradle

inputs:
  - name: music-repo
  - name: version

outputs:
  - name: music-repo
    path: music-repo  

run:
  path: music-repo/ci/tasks/build-artifact.sh
